// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzh5QQvLCg8YPfTfZHKeJYmqv3pDnQn8k',
    appId: '1:567779138867:web:fe73a4d9a25eb37568b246',
    messagingSenderId: '567779138867',
    projectId: 'task-management-app-8b634',
    authDomain: 'task-management-app-8b634.firebaseapp.com',
    storageBucket: 'task-management-app-8b634.appspot.com',
    measurementId: 'G-MWBE30HKS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHUu3VZHknzOe2QscJDutdxcmrODT1xVs',
    appId: '1:567779138867:android:abb36ecc2a1146cb68b246',
    messagingSenderId: '567779138867',
    projectId: 'task-management-app-8b634',
    storageBucket: 'task-management-app-8b634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8GeJ-3sdSo2wAWE3VJ0S_M5THZT2RKc',
    appId: '1:567779138867:ios:a246ae055325c5f368b246',
    messagingSenderId: '567779138867',
    projectId: 'task-management-app-8b634',
    storageBucket: 'task-management-app-8b634.appspot.com',
    iosBundleId: 'com.example.tastManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8GeJ-3sdSo2wAWE3VJ0S_M5THZT2RKc',
    appId: '1:567779138867:ios:a246ae055325c5f368b246',
    messagingSenderId: '567779138867',
    projectId: 'task-management-app-8b634',
    storageBucket: 'task-management-app-8b634.appspot.com',
    iosBundleId: 'com.example.tastManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzh5QQvLCg8YPfTfZHKeJYmqv3pDnQn8k',
    appId: '1:567779138867:web:f40e77edb508da3a68b246',
    messagingSenderId: '567779138867',
    projectId: 'task-management-app-8b634',
    authDomain: 'task-management-app-8b634.firebaseapp.com',
    storageBucket: 'task-management-app-8b634.appspot.com',
    measurementId: 'G-S11YGHX22L',
  );
}
